"""Data models for attack chain discovery and LLM reasoning output.

These models flow through the pipeline:

  Attack Path Engine (M7/M8) → produces CandidateChain
  Reasoning Agent (M10)      → consumes CandidateChain, produces ValidatedChain
  Report Generator (M11)     → consumes ValidatedChain

All models that represent final security findings (ValidatedChain, AttackStep,
ConfidenceBreakdown) are immutable (frozen=True).  Security findings must not
be mutated after agent validation.

Module dependency: imports only from api_analyzer.models.enums.
"""

import re
import statistics
from datetime import datetime

from pydantic import BaseModel, ConfigDict, Field, computed_field, field_validator

from api_analyzer.models.enums import Severity
from api_analyzer.models.probe import ProbeResult

# MITRE ATT&CK technique ID format: T1234 or T1234.567 (sub-technique)
_MITRE_ID_PATTERN: re.Pattern[str] = re.compile(r"^T\d{4}(\.\d{3})?$")

# Maximum tool calls the reasoning agent (M10) is expected to make per chain.
# The evidence bonus in ConfidenceBreakdown.final_score saturates at this count.
# Update when M10's MAX_TOOL_CALLS_PER_CHAIN constant changes.
_MAX_EVIDENCE_COUNT: int = 5


class CandidateChain(BaseModel):
    """A candidate attack chain produced by the attack path engine (M8).

    Represents a multi-hop path through the Neo4j knowledge graph that matched
    one or more OWASP attack pattern templates.  Not yet LLM-validated.

    The ``rank_score`` field determines priority when the candidate count
    exceeds the LLM analysis budget (``MAX_CANDIDATES_PER_ANALYSIS``).
    Higher-ranked candidates are analysed first; lower-ranked ones may be
    excluded entirely if the budget is exhausted.

    All fields are set at construction time; the model is immutable.
    """

    model_config = ConfigDict(frozen=True)

    id: str = Field(description="UUID generated at creation time by the engine")
    pattern_id: str = Field(description="ID of the YAML pattern template that found this chain")
    pattern_name: str
    owasp_category: str = Field(description="OWASP API Security category, e.g. 'API1:2023'")
    mitre_hints: list[str] = Field(
        default_factory=list,
        description=(
            "Technique IDs from the pattern YAML, e.g. ['T1589.001', 'T1530']. "
            "Not yet validated against the MITRE bundle — validation happens in M10."
        ),
    )
    confidence_base: float = Field(
        ge=0.0,
        le=1.0,
        description="Starting confidence from the pattern YAML before LLM validation",
    )
    endpoint_ids: list[str] = Field(
        min_length=2,
        description="Ordered endpoint IDs from entry to exit, at least 2 endpoints",
    )
    hop_count: int = Field(
        ge=1,
        description="Number of edges traversed = len(endpoint_ids) - 1",
    )
    entry_endpoint_id: str = Field(description="ID of the first (attacker entry) endpoint")
    exit_endpoint_id: str = Field(description="ID of the last (target) endpoint")
    crosses_auth_boundary: bool = Field(
        description=(
            "True if the chain moves from a public endpoint to an authenticated one. "
            "Chains that cross the auth boundary are ranked higher."
        ),
    )
    sensitivity_delta: int = Field(
        ge=0,
        description=(
            "SensitivityClass index difference between entry and exit endpoints (0–3). "
            "Higher delta = higher analysis priority."
        ),
    )
    rank_score: float = Field(
        ge=0.0,
        description="Composite priority score from the ranker (M8). Higher = higher priority.",
    )
    entry_summary: str = Field(
        description="Human-readable entry point, e.g. 'GET /users (PUBLIC)'"
    )
    exit_summary: str = Field(
        description="Human-readable exit point, e.g. 'GET /users/{id}/data (SENSITIVE)'"
    )


class AttackStep(BaseModel):
    """One hop in a validated attack chain.

    Each step describes what an attacker does at a specific endpoint, what
    they gain from it, and how that output feeds into the next step.
    Generated by the LLM reasoning agent (M10).

    ``auth_required`` is a free-text string rather than an enum because
    realistic auth requirements are nuanced: 'any valid Bearer token, not
    necessarily the resource owner' is meaningfully different from 'admin-role
    Bearer token', and an enum would lose that distinction.
    """

    model_config = ConfigDict(frozen=True)

    sequence: int = Field(ge=1, description="1-indexed position in the chain")
    endpoint_id: str = Field(description="Endpoint ID in format 'METHOD:path'")
    path: str = Field(description="URL path, e.g. '/users/{userId}'")
    method: str = Field(description="HTTP method in uppercase")
    auth_required: str = Field(
        description=(
            "Natural language description of authentication at this step. "
            "Examples: 'None — public endpoint', 'Any valid Bearer token', "
            "'Admin-scoped Bearer token'"
        ),
    )
    action: str = Field(
        description="What the attacker does at this endpoint, e.g. 'Enumerate user IDs'"
    )
    attacker_gains: str = Field(
        description="What the attacker obtains from this step for use in subsequent hops"
    )
    technique: str = Field(
        description="Vulnerability technique applied, e.g. 'Integer enumeration via predictable IDs'"
    )

    @field_validator("action", "attacker_gains", "technique", "auth_required")
    @classmethod
    def reject_empty_llm_strings(cls, v: str) -> str:
        """Prevent empty or whitespace-only LLM outputs from silently passing.

        The reasoning agent occasionally returns empty strings for fields it
        could not determine.  Catching them here forces a retry rather than
        allowing a malformed step to propagate into a report.
        """
        stripped = v.strip()
        if not stripped:
            raise ValueError(
                "LLM-generated AttackStep fields must not be empty or whitespace-only. "
                "The reasoning agent should retry this chain analysis."
            )
        return stripped


class ConfidenceBreakdown(BaseModel):
    """Transparent decomposition of an attack chain's confidence score.

    The ``final_score`` is a ``@computed_field`` derived from three component
    scores using geometric mean — chosen because it penalises weakness in any
    single component more severely than arithmetic mean.

    Example: graph_match=1.0, auth_clarity=1.0, llm_self=0.0 → final=0.0
    With arithmetic mean this would be 0.67 and the chain would pass the
    0.4 threshold as a false positive.  Geometric mean kills it correctly.

    ``evidence_count`` provides a small upward adjustment (max +5%) for chains
    with multiple independent tool-call confirmations.  It does not rescue
    chains with weak component scores.
    """

    model_config = ConfigDict(frozen=True)

    graph_match_score: float = Field(
        ge=0.0,
        le=1.0,
        description="Pattern template match quality, set by the ranker (M8)",
    )
    auth_clarity_score: float = Field(
        ge=0.0,
        le=1.0,
        description=(
            "How explicitly auth requirements are declared in the spec. "
            "Derived from ParsedSpec.spec_completeness and per-endpoint auth declarations."
        ),
    )
    llm_self_score: float = Field(
        ge=0.0,
        le=1.0,
        description="The agent's self-assessed confidence after graph tool-call validation",
    )
    evidence_count: int = Field(
        ge=0,
        description="Number of graph tool calls that returned supporting evidence for this chain",
    )
    rationale: str = Field(
        description="LLM explanation of the assigned confidence level"
    )

    @computed_field  # type: ignore[prop-decorator]
    @property
    def final_score(self) -> float:
        """Geometric mean of component scores adjusted by evidence count.

        Returns 0.0 immediately if any component score is exactly 0.0 or
        negative, because ``statistics.geometric_mean`` requires strictly
        positive inputs.

        Evidence bonus: up to +5% for 5 or more supporting tool call results.
        Final score capped at 1.0.
        """
        scores = [self.graph_match_score, self.auth_clarity_score, self.llm_self_score]
        # Guard: geometric_mean requires strictly positive, non-empty input.
        # The list is always length 3 (hardcoded above), so emptiness cannot occur,
        # but the zero guard is essential — any zero component kills confidence.
        if any(s <= 0.0 for s in scores):
            return 0.0
        base = statistics.geometric_mean(scores)
        evidence_bonus = min(self.evidence_count / _MAX_EVIDENCE_COUNT, 1.0) * 0.05
        return round(min(base + evidence_bonus, 1.0), 4)


class ValidatedChain(BaseModel):
    """A fully validated attack chain — the primary output of the reasoning agent.

    This is an immutable security finding.  Once the LLM agent has validated a
    candidate chain and the Pydantic validator has accepted the structured output,
    the finding must not be mutated.

    The ``confidence`` field embeds the full ``ConfidenceBreakdown`` rather than
    a plain float.  This enables the report generator (M11) to render a
    transparent score breakdown alongside the numeric value — distinguishing
    this tool from black-box scanners where an opaque 'confidence: 0.87'
    cannot be audited or challenged.

    MITRE technique IDs are validated at construction time against the expected
    format (T1234 or T1234.567).  A second validation against the local MITRE
    bundle occurs in the reasoning agent (M10) before this model is constructed.
    """

    model_config = ConfigDict(frozen=True)

    id: str = Field(description="UUID carried from CandidateChain.id")
    candidate_id: str = Field(description="CandidateChain.id this finding was derived from")
    pattern_id: str
    name: str = Field(
        description="Human-readable chain name, e.g. 'BOLA → Mass PII Exfiltration'"
    )
    severity: Severity
    confidence: ConfidenceBreakdown
    steps: list[AttackStep] = Field(
        min_length=2,
        description="Ordered exploitation steps from entry to exit, minimum 2",
    )
    narrative: str = Field(
        description="Exploitation story written by the LLM agent (minimum 100 characters)"
    )
    mitre_techniques: list[str] = Field(
        default_factory=list,
        description=(
            "Validated MITRE ATT&CK technique IDs. Format-checked here; "
            "existence-checked against the local bundle in M10."
        ),
    )
    owasp_category: str = Field(
        description="OWASP API Security category, e.g. 'API1:2023 Broken Object Level Authorization'"
    )
    remediation: list[str] = Field(
        min_length=1,
        description="Ordered remediation steps, at least one required",
    )
    tool_calls_used: list[str] = Field(
        default_factory=list,
        description=(
            "Transparency log: descriptions of graph tool calls the agent made. "
            "Example: 'get_endpoint(GET:/users) → is_public=True, returns_collection=True'"
        ),
    )
    probe_result: ProbeResult | None = Field(
        default=None,
        description=(
            "Runtime HTTP probe result for the entry endpoint. None when no target_url "
            "was provided. CONFIRMED means the endpoint responded 2xx without auth."
        ),
    )
    analyzed_at: datetime = Field(description="UTC timestamp when the agent produced this finding")
    llm_model: str = Field(
        description=(
            "Model identifier used for this analysis, e.g. 'claude-sonnet-4-6'. "
            "Stored for research paper reproducibility and cross-model comparison."
        )
    )
    tokens_used: int = Field(
        ge=0,
        description="Total input + output tokens consumed for this chain's analysis",
    )

    @field_validator("mitre_techniques")
    @classmethod
    def validate_mitre_id_format(cls, v: list[str]) -> list[str]:
        """Reject MITRE technique IDs that do not match the standard format.

        This is the primary defence against hallucinated technique IDs.  The
        LLM occasionally invents plausible-looking but non-existent IDs such as
        'T9999' or 'T1078.999'.  Format validation here catches structural
        errors; existence validation against the local MITRE bundle in M10
        catches valid-format but non-existent IDs.
        """
        for technique_id in v:
            if not _MITRE_ID_PATTERN.match(technique_id):
                raise ValueError(
                    f"Invalid MITRE ATT&CK technique ID: {technique_id!r}. "
                    "Expected format: T1234 or T1234.567 (sub-technique)"
                )
        return v

    @field_validator("narrative")
    @classmethod
    def validate_narrative_minimum_length(cls, v: str) -> str:
        """Reject trivially short narratives that provide no analytical value.

        The reasoning agent should produce a multi-paragraph exploitation story.
        A narrative under 100 characters indicates a truncated or failed
        generation that should trigger a retry in M10.
        """
        stripped = v.strip()
        if len(stripped) < 100:
            raise ValueError(
                f"Narrative is too short ({len(stripped)} chars, minimum 100). "
                "The reasoning agent should produce a multi-paragraph exploitation story."
            )
        return stripped
