"""Neo4j graph layer for the API Attack Path Analyzer."""

from api_analyzer.graph.queries import (
    AuthChainCandidate,
    BolaCandidate,
    BrokenAuthCandidate,
    ExcessiveDataCandidate,
    MassAssignmentCandidate,
    PrivEscCandidate,
    SsrfCandidate,
    find_auth_chain_candidates,
    find_bola_candidates,
    find_broken_auth_candidates,
    find_excessive_data_candidates,
    find_mass_assignment_candidates,
    find_priv_esc_candidates,
    find_ssrf_candidates,
    get_endpoint_count,
    get_spec_completeness,
)
from api_analyzer.graph.schema import (
    CONSTRAINTS,
    INDEXES,
    LABEL_API_SPEC,
    LABEL_AUTH_SCHEME,
    LABEL_ENDPOINT,
    LABEL_RESOURCE,
    PROP_AUTH_DECLARED,
    PROP_AUTH_SCHEME_NAMES,
    PROP_AUTH_TYPE,
    PROP_ID,
    PROP_IDENTIFIER_TYPE,
    PROP_INFERRED_FUNCTION,
    PROP_IS_JWT,
    PROP_IS_PUBLIC,
    PROP_METHOD,
    PROP_NAME,
    PROP_PATH,
    PROP_PATH_PREFIX,
    PROP_SENSITIVITY_CLASS,
    PROP_SPEC_COMPLETENESS,
    PROP_SPEC_FORMAT,
    PROP_SPEC_ID,
    PROP_TITLE,
    PROP_VERSION,
    REL_CHILD_OF,
    REL_DELETES,
    REL_LISTS,
    REL_PART_OF,
    REL_READS,
    REL_REQUIRES_AUTH,
    REL_WRITES,
    apply_schema,
    make_spec_id,
    wipe_spec,
)

__all__ = [
    # Node labels
    "LABEL_API_SPEC",
    "LABEL_AUTH_SCHEME",
    "LABEL_ENDPOINT",
    "LABEL_RESOURCE",
    # Relationship types
    "REL_CHILD_OF",
    "REL_DELETES",
    "REL_LISTS",
    "REL_PART_OF",
    "REL_READS",
    "REL_REQUIRES_AUTH",
    "REL_WRITES",
    # Property keys
    "PROP_AUTH_DECLARED",
    "PROP_AUTH_SCHEME_NAMES",
    "PROP_AUTH_TYPE",
    "PROP_ID",
    "PROP_IDENTIFIER_TYPE",
    "PROP_INFERRED_FUNCTION",
    "PROP_IS_JWT",
    "PROP_IS_PUBLIC",
    "PROP_METHOD",
    "PROP_NAME",
    "PROP_PATH",
    "PROP_PATH_PREFIX",
    "PROP_SENSITIVITY_CLASS",
    "PROP_SPEC_COMPLETENESS",
    "PROP_SPEC_FORMAT",
    "PROP_SPEC_ID",
    "PROP_TITLE",
    "PROP_VERSION",
    # DDL lists
    "CONSTRAINTS",
    "INDEXES",
    # Functions
    "apply_schema",
    "make_spec_id",
    "wipe_spec",
    # Query functions
    "find_auth_chain_candidates",
    "find_bola_candidates",
    "find_broken_auth_candidates",
    "find_excessive_data_candidates",
    "find_mass_assignment_candidates",
    "find_priv_esc_candidates",
    "find_ssrf_candidates",
    "get_endpoint_count",
    "get_spec_completeness",
    # Candidate dataclasses
    "AuthChainCandidate",
    "BolaCandidate",
    "BrokenAuthCandidate",
    "ExcessiveDataCandidate",
    "MassAssignmentCandidate",
    "PrivEscCandidate",
    "SsrfCandidate",
]
